export const CATEGORIES_ACTION_TYPES = {
  FETCH_CATEGORIES_START: "category/FETCH_CATEGORIES_START",
  FETCH_CATEGORIES_SUCCESS: "category/FETCH_CATEGORIES_SUCCESS",
  FETCH_CATEGORIES_FAILED: "category/FETCH_CATEGORIES_FAILED",

  FETCH_PRODUCT_START: "category/FETCH_PRODUCT_START",
  FETCH_PRODUCT_SUCCESS: "category/FETCH_PRODUCT_SUCCESS",
  FETCH_PRODUCT_FAILED: "category/FETCH_PRODUCT_FAILED",
};
