const DC_SHOP_DATA2 = [
  {
    title: "Batman",
    items: [
      {
        id: 1,
        title: "Gotham Night Graphic T-Shirt",
        slug: "gotham-night-graphic-tshirt",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Batman",
        price: 24.99,
        originalPrice: 29.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 342,
        stock: 42,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Charcoal"],
        image: "/products/batman-gotham-night.webp",
        description:
          "A relaxed-fit graphic tee inspired by Gotham City's legendary protector.",
        features: [
          "100% cotton",
          "Relaxed fit",
          "Screen-printed graphic",
          "Machine washable",
        ],
        isFeatured: true,
        isSale: true,
      },
      {
        id: 2,
        title: "Dark Knight Emblem T-Shirt",
        slug: "dark-knight-emblem-tshirt",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Batman",
        price: 27.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 218,
        stock: 31,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Navy"],
        image: "/products/batman-emblem.webp",
        description:
          "Minimalist Batman-inspired tee featuring a bold chest emblem.",
        features: [
          "Premium cotton blend",
          "Regular fit",
          "Soft-touch fabric",
          "Reinforced collar",
        ],
        isFeatured: true,
      },
      {
        id: 3,
        title: "Gotham City Oversized Tee",
        slug: "gotham-city-oversized-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Batman",
        price: 29.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 156,
        stock: 25,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Washed Black", "Stone"],
        image: "/products/gotham-oversized.webp",
        description:
          "Oversized streetwear tee featuring a Gotham City graphic.",
        features: [
          "Oversized fit",
          "Heavyweight cotton",
          "Dropped shoulders",
          "Vintage wash",
        ],
        isNew: true,
      },
      {
        id: 4,
        title: "Batman Shadow Hoodie",
        slug: "batman-shadow-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Batman",
        price: 54.99,
        originalPrice: 64.99,
        currency: "USD",
        rating: 4.9,
        reviewCount: 489,
        stock: 18,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Dark Gray"],
        image: "/products/batman-shadow-hoodie.webp",
        description:
          "Heavyweight hoodie with a subtle Batman-inspired chest design.",
        features: [
          "Heavyweight fleece",
          "Adjustable hood",
          "Kangaroo pocket",
          "Ribbed cuffs",
        ],
        isFeatured: true,
        isSale: true,
      },
      {
        id: 5,
        title: "Gotham Guardian Zip Hoodie",
        slug: "gotham-guardian-zip-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Batman",
        price: 59.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 203,
        stock: 14,
        sizes: ["M", "L", "XL", "XXL"],
        colors: ["Black", "Charcoal"],
        image: "/products/gotham-guardian.webp",
        description:
          "Full-zip streetwear hoodie designed for a clean Gotham-inspired look.",
        features: [
          "Full-length zipper",
          "Cotton fleece",
          "Two side pockets",
          "Adjustable drawcord",
        ],
      },
      {
        id: 6,
        title: "Wayne Industries Varsity Jacket",
        slug: "wayne-industries-varsity-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "Batman",
        price: 89.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 127,
        stock: 9,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Black/Gray"],
        image: "/products/wayne-varsity.webp",
        description:
          "Premium varsity-style jacket inspired by Gotham's iconic Wayne legacy.",
        features: [
          "Wool-blend body",
          "Faux leather sleeves",
          "Snap-button closure",
          "Embroidered details",
        ],
        isNew: true,
        isFeatured: true,
      },
      {
        id: 7,
        title: "Batman Utility Joggers",
        slug: "batman-utility-joggers",
        brand: "MetaWear",
        category: "Pants",
        character: "Batman",
        price: 49.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 98,
        stock: 22,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Dark Gray"],
        image: "/products/batman-joggers.webp",
        description:
          "Tapered utility joggers with subtle Batman-inspired detailing.",
        features: [
          "Stretch cotton",
          "Tapered fit",
          "Six utility pockets",
          "Elastic waistband",
        ],
      },
      {
        id: 8,
        title: "Gotham Baseball Cap",
        slug: "gotham-baseball-cap",
        brand: "MetaWear",
        category: "Accessories",
        character: "Batman",
        price: 22.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 318,
        stock: 47,
        sizes: ["One Size"],
        colors: ["White", "Charcoal"],
        image: "/products/gotham-cap.webp",
        description:
          "Classic six-panel cap featuring a subtle Gotham-inspired emblem.",
        features: [
          "Adjustable strap",
          "Six-panel construction",
          "Embroidered emblem",
          "Curved brim",
        ],
      },
      {
        id: 9,
        title: "Gotham After Dark Hoodie",
        slug: "gotham-after-dark-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Batman",
        price: 61.99,
        currency: "USD",
        rating: 4.9,
        reviewCount: 431,
        stock: 11,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Midnight Blue"],
        image: "/products/gotham-after-dark.webp",
        description:
          "Premium oversized hoodie inspired by Gotham's nighttime atmosphere.",
        features: [
          "Heavyweight fleece",
          "Oversized fit",
          "Embroidered graphic",
          "Double-layer hood",
        ],
        isFeatured: true,
      },
      {
        id: 10,
        title: "Dark Knight Street Joggers",
        slug: "dark-knight-street-joggers",
        brand: "MetaWear",
        category: "Pants",
        character: "Batman",
        price: 51.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 117,
        stock: 18,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Charcoal"],
        image: "/products/dark-knight-joggers.webp",
        description:
          "Streetwear joggers featuring subtle reflective Batman-inspired details.",
        features: [
          "Stretch fabric",
          "Tapered silhouette",
          "Reflective details",
          "Zipper pockets",
        ],
      },
    ],
  },

  {
    title: "Superman",
    items: [
      {
        id: 11,
        title: "Man of Steel Classic Tee",
        slug: "man-of-steel-classic-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Superman",
        price: 26.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 376,
        stock: 37,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Navy", "Black", "Royal Blue"],
        image: "/products/superman-classic.webp",
        description:
          "Classic Superman-inspired T-shirt featuring a bold chest emblem.",
        features: [
          "100% cotton",
          "Regular fit",
          "Printed emblem",
          "Soft fabric",
        ],
        isFeatured: true,
      },
      {
        id: 12,
        title: "Metropolis Skyline T-Shirt",
        slug: "metropolis-skyline-tshirt",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Superman",
        price: 28.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 141,
        stock: 29,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Navy"],
        image: "/products/metropolis-skyline.webp",
        description:
          "Modern graphic tee inspired by the skyline of Metropolis.",
        features: [
          "Cotton jersey",
          "Regular fit",
          "Graphic front print",
          "Tagless neck",
        ],
        isNew: true,
      },
      {
        id: 13,
        title: "Superhero Flight Hoodie",
        slug: "superhero-flight-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Superman",
        price: 57.99,
        originalPrice: 69.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 267,
        stock: 16,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Navy", "Black"],
        image: "/products/superman-flight.webp",
        description: "Warm fleece hoodie inspired by the Man of Steel.",
        features: [
          "Fleece interior",
          "Drawstring hood",
          "Kangaroo pocket",
          "Ribbed hem",
        ],
        isSale: true,
        isFeatured: true,
      },
      {
        id: 14,
        title: "Kryptonian Symbol Sweatshirt",
        slug: "kryptonian-symbol-sweatshirt",
        brand: "MetaWear",
        category: "Sweatshirts",
        character: "Superman",
        price: 44.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 183,
        stock: 21,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Gray", "Navy"],
        image: "/products/kryptonian-sweatshirt.webp",
        description:
          "Clean crewneck sweatshirt with a subtle Kryptonian-inspired emblem.",
        features: [
          "Cotton fleece",
          "Crewneck design",
          "Relaxed fit",
          "Soft brushed interior",
        ],
      },
      {
        id: 15,
        title: "Daily Planet Street Jacket",
        slug: "daily-planet-street-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "Superman",
        price: 79.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 76,
        stock: 11,
        sizes: ["M", "L", "XL"],
        colors: ["Navy", "Black"],
        image: "/products/daily-planet-jacket.webp",
        description:
          "Lightweight street jacket inspired by classic Metropolis style.",
        features: [
          "Water-resistant shell",
          "Zip closure",
          "Three exterior pockets",
          "Lightweight lining",
        ],
      },
      {
        id: 16,
        title: "Kryptonite Warning Tee",
        slug: "kryptonite-warning-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Superman",
        price: 24.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 91,
        stock: 36,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Deep Blue"],
        image: "/products/kryptonite-warning.webp",
        description:
          "Playful Superman-inspired graphic tee built around a kryptonite theme.",
        features: [
          "Cotton jersey",
          "Regular fit",
          "Graphic print",
          "Soft finish",
        ],
      },
      {
        id: 17,
        title: "Metropolis Essential Hoodie",
        slug: "metropolis-essential-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Superman",
        price: 53.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 148,
        stock: 17,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Navy"],
        image: "/products/metropolis-essential.webp",
        description:
          "Minimal everyday hoodie inspired by the city of Metropolis.",
        features: [
          "Midweight fleece",
          "Regular fit",
          "Embroidered chest detail",
          "Kangaroo pocket",
        ],
      },
      {
        id: 18,
        title: "Superman Heritage Cap",
        slug: "superman-heritage-cap",
        brand: "MetaWear",
        category: "Accessories",
        character: "Superman",
        price: 21.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 127,
        stock: 43,
        sizes: ["One Size"],
        colors: ["White", "Navy"],
        image: "/products/superman-cap.webp",
        description:
          "Classic adjustable cap featuring a clean Superman-inspired emblem.",
        features: [
          "Adjustable closure",
          "Cotton twill",
          "Embroidered emblem",
          "Curved brim",
        ],
      },
      {
        id: 19,
        title: "Man of Steel Track Pants",
        slug: "man-of-steel-track-pants",
        brand: "MetaWear",
        category: "Pants",
        character: "Superman",
        price: 47.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 88,
        stock: 20,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Navy", "White"],
        image: "/products/superman-track-pants.webp",
        description:
          "Comfortable tapered track pants with subtle superhero-inspired details.",
        features: [
          "Stretch fabric",
          "Tapered fit",
          "Zipper pockets",
          "Elastic cuffs",
        ],
      },
      {
        id: 20,
        title: "Metropolis Flight Jacket",
        slug: "metropolis-flight-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "Superman",
        price: 84.99,
        originalPrice: 99.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 104,
        stock: 8,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Royal Blue"],
        image: "/products/metropolis-flight-jacket.webp",
        description:
          "Premium lightweight bomber inspired by the colors of Metropolis.",
        features: [
          "Water-resistant shell",
          "Lightweight lining",
          "Zip pockets",
          "Ribbed collar",
        ],
        isSale: true,
        isFeatured: true,
      },
    ],
  },

  {
    title: "Wonder Woman",
    items: [
      {
        id: 21,
        title: "Amazon Warrior Graphic Tee",
        slug: "amazon-warrior-graphic-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Wonder Woman",
        price: 25.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 312,
        stock: 34,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black", "Burgundy"],
        image: "/products/wonder-woman-warrior.webp",
        description:
          "Bold graphic tee inspired by the legendary Amazon warrior.",
        features: [
          "Cotton jersey",
          "Women's relaxed fit",
          "Graphic print",
          "Soft finish",
        ],
        isFeatured: true,
      },
      {
        id: 22,
        title: "Wonder Warrior Crop Hoodie",
        slug: "wonder-warrior-crop-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Wonder Woman",
        price: 52.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 198,
        stock: 19,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black", "Red"],
        image: "/products/wonder-woman-crop.webp",
        description:
          "Cropped fleece hoodie featuring a bold warrior-inspired graphic.",
        features: [
          "Cropped fit",
          "Fleece interior",
          "Drawstring hood",
          "Ribbed cuffs",
        ],
        isNew: true,
      },
      {
        id: 23,
        title: "Themyscira Athletic Sweatshirt",
        slug: "themyscira-athletic-sweatshirt",
        brand: "MetaWear",
        category: "Sweatshirts",
        character: "Wonder Woman",
        price: 46.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 109,
        stock: 27,
        sizes: ["XS", "S", "M", "L"],
        colors: ["Gray", "Burgundy"],
        image: "/products/themyscira-sweatshirt.webp",
        description:
          "Athletic-inspired sweatshirt with subtle Themyscira details.",
        features: [
          "Midweight fleece",
          "Relaxed fit",
          "Embroidered emblem",
          "Cotton blend",
        ],
      },
      {
        id: 24,
        title: "Amazon Champion Training Shorts",
        slug: "amazon-champion-training-shorts",
        brand: "MetaWear",
        category: "Shorts",
        character: "Wonder Woman",
        price: 34.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 87,
        stock: 24,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black", "Red"],
        image: "/products/wonder-woman-shorts.webp",
        description:
          "Lightweight athletic shorts designed for training and everyday wear.",
        features: [
          "Lightweight fabric",
          "Elastic waistband",
          "Side pockets",
          "Quick-dry finish",
        ],
      },
      {
        id: 25,
        title: "Amazon Legacy T-Shirt",
        slug: "amazon-legacy-tshirt",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Wonder Woman",
        price: 27.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 136,
        stock: 22,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Black", "Cream"],
        image: "/products/amazon-legacy.webp",
        description: "Elegant graphic tee inspired by Amazonian heritage.",
        features: [
          "Premium cotton",
          "Relaxed women's fit",
          "Screen print",
          "Soft-washed finish",
        ],
      },
      {
        id: 26,
        title: "Themyscira Heritage Hoodie",
        slug: "themyscira-heritage-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Wonder Woman",
        price: 58.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 154,
        stock: 16,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Burgundy", "White"],
        image: "/products/themyscira-hoodie.webp",
        description: "Premium fleece hoodie inspired by Amazonian heritage.",
        features: [
          "Premium fleece",
          "Relaxed fit",
          "Embroidered emblem",
          "Kangaroo pocket",
        ],
      },
      {
        id: 27,
        title: "Amazon Warrior Joggers",
        slug: "amazon-warrior-joggers",
        brand: "MetaWear",
        category: "Pants",
        character: "Wonder Woman",
        price: 48.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 92,
        stock: 18,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["White", "Burgundy"],
        image: "/products/amazon-joggers.webp",
        description:
          "Tapered joggers featuring subtle Amazon-inspired accents.",
        features: [
          "Stretch cotton",
          "Tapered fit",
          "Side pockets",
          "Elastic cuffs",
        ],
      },
      {
        id: 28,
        title: "Warrior Spirit Jacket",
        slug: "warrior-spirit-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "Wonder Woman",
        price: 79.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 83,
        stock: 10,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["White", "Burgundy"],
        image: "/products/warrior-spirit-jacket.webp",
        description:
          "Modern utility jacket inspired by Amazonian warrior aesthetics.",
        features: [
          "Cotton twill",
          "Utility pockets",
          "Zip closure",
          "Relaxed fit",
        ],
        isNew: true,
      },
      {
        id: 29,
        title: "Amazon Champion Cap",
        slug: "amazon-champion-cap",
        brand: "MetaWear",
        category: "Accessories",
        character: "Wonder Woman",
        price: 22.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 74,
        stock: 31,
        sizes: ["One Size"],
        colors: ["White", "Red"],
        image: "/products/wonder-woman-cap.webp",
        description:
          "Classic baseball cap featuring a subtle warrior-inspired emblem.",
        features: [
          "Adjustable strap",
          "Cotton twill",
          "Embroidered emblem",
          "Curved brim",
        ],
      },
      {
        id: 30,
        title: "Amazon Training Tank",
        slug: "amazon-training-tank",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Wonder Woman",
        price: 23.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 118,
        stock: 25,
        sizes: ["XS", "S", "M", "L", "XL"],
        colors: ["Gold", "Red", "White"],
        image: "/products/amazon-training-tank.webp",
        description:
          "Lightweight athletic tank inspired by Amazonian training gear.",
        features: [
          "Breathable fabric",
          "Athletic fit",
          "Moisture-wicking",
          "Stretch construction",
        ],
      },
    ],
  },

  {
    title: "The Flash",
    items: [
      {
        id: 31,
        title: "Speed Force Graphic Tee",
        slug: "speed-force-graphic-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "The Flash",
        price: 25.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 291,
        stock: 39,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Red"],
        image: "/products/flash-speed-force.webp",
        description:
          "Dynamic Flash-inspired graphic tee designed for everyday streetwear.",
        features: [
          "Cotton jersey",
          "Regular fit",
          "High-detail graphic",
          "Machine washable",
        ],
        isFeatured: true,
      },
      {
        id: 32,
        title: "Central City Runner Hoodie",
        slug: "central-city-runner-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "The Flash",
        price: 55.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 173,
        stock: 15,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Dark Red"],
        image: "/products/flash-runner.webp",
        description:
          "Sporty fleece hoodie inspired by Central City's fastest hero.",
        features: [
          "Performance fleece",
          "Athletic fit",
          "Zip pocket",
          "Adjustable hood",
        ],
      },
      {
        id: 33,
        title: "Speed Force Track Jacket",
        slug: "speed-force-track-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "The Flash",
        price: 69.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 94,
        stock: 12,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black/Red", "Red"],
        image: "/products/flash-track-jacket.webp",
        description: "Lightweight track jacket with racing-inspired details.",
        features: [
          "Lightweight shell",
          "Full zip",
          "Elastic cuffs",
          "Reflective accents",
        ],
        isNew: true,
      },
      {
        id: 34,
        title: "Fastest Man Joggers",
        slug: "fastest-man-joggers",
        brand: "MetaWear",
        category: "Pants",
        character: "The Flash",
        price: 49.99,
        originalPrice: 59.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 132,
        stock: 20,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Red"],
        image: "/products/flash-joggers.webp",
        description:
          "Tapered performance joggers with subtle speed-inspired accents.",
        features: [
          "Stretch fabric",
          "Tapered leg",
          "Zipper pockets",
          "Elastic cuffs",
        ],
        isSale: true,
      },
      {
        id: 35,
        title: "Speedster Performance Tee",
        slug: "speedster-performance-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "The Flash",
        price: 31.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 102,
        stock: 30,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Red"],
        image: "/products/speedster-performance.webp",
        description:
          "Lightweight performance shirt inspired by the Speed Force.",
        features: [
          "Moisture-wicking fabric",
          "Athletic fit",
          "Four-way stretch",
          "Breathable panels",
        ],
        isNew: true,
      },
      {
        id: 36,
        title: "Central City Track Pants",
        slug: "central-city-track-pants",
        brand: "MetaWear",
        category: "Pants",
        character: "The Flash",
        price: 45.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 72,
        stock: 15,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Red"],
        image: "/products/central-city-pants.webp",
        description:
          "Lightweight track pants with speed-inspired red detailing.",
        features: [
          "Performance fabric",
          "Tapered fit",
          "Zip ankle openings",
          "Two side pockets",
        ],
      },
      {
        id: 37,
        title: "Speed Force Running Shorts",
        slug: "speed-force-running-shorts",
        brand: "MetaWear",
        category: "Shorts",
        character: "The Flash",
        price: 29.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 86,
        stock: 28,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Red"],
        image: "/products/flash-running-shorts.webp",
        description:
          "Lightweight running shorts designed around a speed-inspired aesthetic.",
        features: [
          "Quick-dry fabric",
          "Elastic waistband",
          "Inner liner",
          "Reflective accents",
        ],
      },
      {
        id: 38,
        title: "Central City Baseball Cap",
        slug: "central-city-baseball-cap",
        brand: "MetaWear",
        category: "Accessories",
        character: "The Flash",
        price: 21.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 97,
        stock: 35,
        sizes: ["One Size"],
        colors: ["White", "Red"],
        image: "/products/flash-cap.webp",
        description: "Adjustable cap featuring a subtle speed-inspired emblem.",
        features: [
          "Adjustable strap",
          "Cotton twill",
          "Embroidered detail",
          "Curved brim",
        ],
      },
      {
        id: 39,
        title: "Speedster Training Hoodie",
        slug: "speedster-training-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "The Flash",
        price: 59.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 144,
        stock: 13,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Dark Red"],
        image: "/products/speedster-training.webp",
        description:
          "Athletic hoodie built around a fast-paced training aesthetic.",
        features: [
          "Performance fleece",
          "Athletic fit",
          "Thumb-hole cuffs",
          "Adjustable hood",
        ],
        isFeatured: true,
      },
      {
        id: 40,
        title: "Velocity Bomber Jacket",
        slug: "velocity-bomber-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "The Flash",
        price: 82.99,
        originalPrice: 94.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 71,
        stock: 9,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Red"],
        image: "/products/flash-bomber.webp",
        description: "Modern bomber jacket with bold speed-inspired detailing.",
        features: [
          "Water-resistant shell",
          "Lightweight lining",
          "Zip pockets",
          "Ribbed collar",
        ],
        isSale: true,
      },
    ],
  },

  {
    title: "Aquaman",
    items: [
      {
        id: 41,
        title: "King of Atlantis Tee",
        slug: "king-of-atlantis-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Aquaman",
        price: 26.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 154,
        stock: 28,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Deep Green"],
        image: "/products/aquaman-atlantis.webp",
        description:
          "Ocean-inspired graphic tee celebrating the legendary King of Atlantis.",
        features: [
          "100% cotton",
          "Relaxed fit",
          "Graphic print",
          "Soft finish",
        ],
      },
      {
        id: 42,
        title: "Atlantis Wave Hoodie",
        slug: "atlantis-wave-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Aquaman",
        price: 56.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 118,
        stock: 13,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Dark Green", "Black"],
        image: "/products/atlantis-wave.webp",
        description:
          "Heavyweight hoodie featuring an ocean-inspired graphic design.",
        features: [
          "Heavyweight fleece",
          "Kangaroo pocket",
          "Drawstring hood",
          "Relaxed fit",
        ],
      },
      {
        id: 43,
        title: "Ocean Guardian Oversized Tee",
        slug: "ocean-guardian-oversized-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Aquaman",
        price: 29.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 73,
        stock: 17,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Washed Black", "Dark Green"],
        image: "/products/ocean-guardian.webp",
        description:
          "Oversized streetwear tee inspired by underwater mythology.",
        features: [
          "Heavyweight cotton",
          "Oversized fit",
          "Vintage wash",
          "Dropped shoulders",
        ],
        isNew: true,
      },
      {
        id: 44,
        title: "Atlantis Heritage Sweatshirt",
        slug: "atlantis-heritage-sweatshirt",
        brand: "MetaWear",
        category: "Sweatshirts",
        character: "Aquaman",
        price: 47.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 83,
        stock: 20,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Deep Green", "Black"],
        image: "/products/atlantis-heritage.webp",
        description:
          "Comfortable crewneck sweatshirt with ocean-inspired artwork.",
        features: [
          "Cotton fleece",
          "Relaxed fit",
          "Embroidered detail",
          "Ribbed cuffs",
        ],
      },
      {
        id: 45,
        title: "Ocean Current Board Shorts",
        slug: "ocean-current-board-shorts",
        brand: "MetaWear",
        category: "Shorts",
        character: "Aquaman",
        price: 36.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 58,
        stock: 23,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black/Green", "Deep Green"],
        image: "/products/ocean-board-shorts.webp",
        description:
          "Quick-dry board shorts featuring subtle ocean-inspired graphics.",
        features: [
          "Quick-dry fabric",
          "Adjustable waistband",
          "Back pocket",
          "Mesh lining",
        ],
      },
      {
        id: 46,
        title: "Atlantis Utility Jacket",
        slug: "atlantis-utility-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "Aquaman",
        price: 76.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 64,
        stock: 12,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Deep Green", "White"],
        image: "/products/atlantis-jacket.webp",
        description:
          "Utility jacket featuring an ocean-inspired color palette.",
        features: [
          "Water-resistant fabric",
          "Multiple pockets",
          "Zip closure",
          "Adjustable cuffs",
        ],
      },
      {
        id: 47,
        title: "Ocean King Joggers",
        slug: "ocean-king-joggers",
        brand: "MetaWear",
        category: "Pants",
        character: "Aquaman",
        price: 48.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 79,
        stock: 18,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Deep Green"],
        image: "/products/aquaman-joggers.webp",
        description:
          "Comfortable tapered joggers with subtle aquatic-inspired accents.",
        features: [
          "Stretch cotton",
          "Tapered fit",
          "Zip pockets",
          "Elastic waistband",
        ],
      },
      {
        id: 48,
        title: "Atlantis Wave Cap",
        slug: "atlantis-wave-cap",
        brand: "MetaWear",
        category: "Accessories",
        character: "Aquaman",
        price: 22.99,
        currency: "USD",
        rating: 4.4,
        reviewCount: 62,
        stock: 29,
        sizes: ["One Size"],
        colors: ["White", "Deep Green"],
        image: "/products/aquaman-cap.webp",
        description: "Everyday cap featuring a subtle wave-inspired design.",
        features: [
          "Adjustable closure",
          "Cotton twill",
          "Embroidered graphic",
          "Curved brim",
        ],
      },
      {
        id: 49,
        title: "Seven Seas Graphic Tee",
        slug: "seven-seas-graphic-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Aquaman",
        price: 27.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 96,
        stock: 32,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Sea Green"],
        image: "/products/seven-seas.webp",
        description:
          "Ocean-themed graphic tee inspired by the legendary Seven Seas.",
        features: [
          "Premium cotton",
          "Regular fit",
          "Graphic front print",
          "Soft finish",
        ],
        isFeatured: true,
      },
      {
        id: 50,
        title: "Trident Street Hoodie",
        slug: "trident-street-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Aquaman",
        price: 60.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 121,
        stock: 14,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Deep Green"],
        image: "/products/trident-hoodie.webp",
        description:
          "Premium streetwear hoodie featuring a bold trident-inspired graphic.",
        features: [
          "Heavyweight fleece",
          "Oversized fit",
          "Embroidered detail",
          "Double-layer hood",
        ],
        isFeatured: true,
      },
    ],
  },

  {
    title: "Green Lantern",
    items: [
      {
        id: 51,
        title: "Emerald Guardian T-Shirt",
        slug: "emerald-guardian-tshirt",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Green Lantern",
        price: 25.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 206,
        stock: 35,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Forest Green"],
        image: "/products/green-lantern.webp",
        description:
          "Green Lantern-inspired graphic tee with an emerald-themed design.",
        features: [
          "Cotton jersey",
          "Regular fit",
          "Screen print",
          "Tagless collar",
        ],
        isFeatured: true,
      },
      {
        id: 52,
        title: "Lantern Corps Hoodie",
        slug: "lantern-corps-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Green Lantern",
        price: 58.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 189,
        stock: 16,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Green"],
        image: "/products/lantern-corps.webp",
        description:
          "Premium fleece hoodie featuring an emerald-inspired chest emblem.",
        features: [
          "Premium fleece",
          "Embroidered emblem",
          "Kangaroo pocket",
          "Adjustable hood",
        ],
      },
      {
        id: 53,
        title: "Emerald Force Joggers",
        slug: "emerald-force-joggers",
        brand: "MetaWear",
        category: "Pants",
        character: "Green Lantern",
        price: 47.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 82,
        stock: 21,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Forest Green"],
        image: "/products/emerald-joggers.webp",
        description: "Comfortable tapered joggers with subtle emerald accents.",
        features: [
          "Stretch cotton",
          "Tapered fit",
          "Zip pockets",
          "Elastic waistband",
        ],
      },
      {
        id: 54,
        title: "Emerald City Essential Tee",
        slug: "emerald-city-essential-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Green Lantern",
        price: 23.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 113,
        stock: 41,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Green"],
        image: "/products/emerald-city.webp",
        description:
          "Minimal Green Lantern-inspired tee designed for everyday wear.",
        features: [
          "100% cotton",
          "Classic fit",
          "Minimal chest graphic",
          "Soft finish",
        ],
      },
      {
        id: 55,
        title: "Guardian Corps Overshirt",
        slug: "guardian-corps-overshirt",
        brand: "MetaWear",
        category: "Jackets",
        character: "Green Lantern",
        price: 74.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 67,
        stock: 10,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Forest Green"],
        image: "/products/guardian-overshirt.webp",
        description:
          "Structured overshirt inspired by futuristic guardian uniforms.",
        features: [
          "Heavy cotton twill",
          "Button closure",
          "Chest pockets",
          "Relaxed fit",
        ],
        isNew: true,
      },
      {
        id: 56,
        title: "Willpower Training Sweatshirt",
        slug: "willpower-training-sweatshirt",
        brand: "MetaWear",
        category: "Sweatshirts",
        character: "Green Lantern",
        price: 45.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 91,
        stock: 17,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Green"],
        image: "/products/willpower-sweatshirt.webp",
        description:
          "Athletic crewneck inspired by the strength and willpower of the Lantern Corps.",
        features: [
          "Midweight fleece",
          "Crewneck design",
          "Relaxed fit",
          "Embroidered emblem",
        ],
      },
      {
        id: 57,
        title: "Lantern Training Shorts",
        slug: "lantern-training-shorts",
        brand: "MetaWear",
        category: "Shorts",
        character: "Green Lantern",
        price: 31.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 64,
        stock: 24,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Green"],
        image: "/products/lantern-shorts.webp",
        description:
          "Lightweight training shorts featuring subtle emerald details.",
        features: [
          "Quick-dry fabric",
          "Elastic waistband",
          "Side pockets",
          "Athletic fit",
        ],
      },
      {
        id: 58,
        title: "Emerald Guardian Cap",
        slug: "emerald-guardian-cap",
        brand: "MetaWear",
        category: "Accessories",
        character: "Green Lantern",
        price: 21.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 83,
        stock: 32,
        sizes: ["One Size"],
        colors: ["White", "Green"],
        image: "/products/green-lantern-cap.webp",
        description: "Classic cap featuring a subtle emerald-inspired emblem.",
        features: [
          "Adjustable strap",
          "Cotton twill",
          "Embroidered detail",
          "Curved brim",
        ],
      },
      {
        id: 59,
        title: "Power Ring Street Hoodie",
        slug: "power-ring-street-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Green Lantern",
        price: 61.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 134,
        stock: 12,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Forest Green"],
        image: "/products/power-ring-hoodie.webp",
        description:
          "Oversized streetwear hoodie with a futuristic emerald-inspired design.",
        features: [
          "Heavyweight fleece",
          "Oversized fit",
          "Embroidered graphic",
          "Kangaroo pocket",
        ],
        isFeatured: true,
      },
      {
        id: 60,
        title: "Lantern Corps Bomber",
        slug: "lantern-corps-bomber",
        brand: "MetaWear",
        category: "Jackets",
        character: "Green Lantern",
        price: 86.99,
        originalPrice: 99.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 59,
        stock: 8,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Green"],
        image: "/products/lantern-bomber.webp",
        description:
          "Premium bomber jacket featuring futuristic Lantern-inspired detailing.",
        features: [
          "Water-resistant shell",
          "Lightweight lining",
          "Zip pockets",
          "Ribbed cuffs",
        ],
        isSale: true,
      },
    ],
  },

  {
    title: "Justice League",
    items: [
      {
        id: 61,
        title: "Justice League United Tee",
        slug: "justice-league-united-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Justice League",
        price: 28.99,
        currency: "USD",
        rating: 4.9,
        reviewCount: 521,
        stock: 44,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "White"],
        image: "/products/justice-league-united.webp",
        description:
          "Classic team-inspired graphic tee celebrating Earth's greatest heroes.",
        features: [
          "100% cotton",
          "Unisex fit",
          "Large back graphic",
          "Soft-touch finish",
        ],
        isFeatured: true,
      },
      {
        id: 62,
        title: "League of Heroes Hoodie",
        slug: "league-of-heroes-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Justice League",
        price: 59.99,
        originalPrice: 69.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 347,
        stock: 23,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Charcoal"],
        image: "/products/justice-league-hoodie.webp",
        description:
          "Heavyweight team hoodie featuring a bold Justice League-inspired graphic.",
        features: [
          "Heavyweight fleece",
          "Unisex fit",
          "Large graphic",
          "Kangaroo pocket",
        ],
        isSale: true,
        isFeatured: true,
      },
      {
        id: 63,
        title: "Justice League Varsity Jacket",
        slug: "justice-league-varsity-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "Justice League",
        price: 99.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 91,
        stock: 8,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Navy"],
        image: "/products/justice-varsity.webp",
        description:
          "Premium varsity jacket inspired by the world's most iconic superhero team.",
        features: [
          "Wool blend",
          "Embroidered patches",
          "Snap closure",
          "Striped ribbing",
        ],
        isNew: true,
        isFeatured: true,
      },
      {
        id: 64,
        title: "League Training Shorts",
        slug: "league-training-shorts",
        brand: "MetaWear",
        category: "Shorts",
        character: "Justice League",
        price: 32.99,
        currency: "USD",
        rating: 4.4,
        reviewCount: 64,
        stock: 26,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Navy"],
        image: "/products/league-shorts.webp",
        description:
          "Lightweight training shorts featuring a subtle team-inspired emblem.",
        features: [
          "Quick-dry fabric",
          "Elastic waistband",
          "Side pockets",
          "Athletic fit",
        ],
      },
      {
        id: 65,
        title: "Heroes Assemble Long Sleeve",
        slug: "heroes-assemble-long-sleeve",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "Justice League",
        price: 31.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 201,
        stock: 27,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "White"],
        image: "/products/heroes-assemble.webp",
        description:
          "Long-sleeve team-inspired shirt with graphic sleeve detailing.",
        features: [
          "Cotton jersey",
          "Regular fit",
          "Printed sleeves",
          "Ribbed cuffs",
        ],
      },
      {
        id: 66,
        title: "Justice League Training Hoodie",
        slug: "justice-league-training-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "Justice League",
        price: 62.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 228,
        stock: 14,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Navy"],
        image: "/products/league-training.webp",
        description:
          "Performance-inspired hoodie designed around a superhero training aesthetic.",
        features: [
          "Performance fleece",
          "Athletic fit",
          "Zip chest pocket",
          "Adjustable hood",
        ],
        isFeatured: true,
      },
      {
        id: 67,
        title: "League Street Joggers",
        slug: "league-street-joggers",
        brand: "MetaWear",
        category: "Pants",
        character: "Justice League",
        price: 52.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 117,
        stock: 19,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Charcoal"],
        image: "/products/league-joggers.webp",
        description:
          "Tapered streetwear joggers featuring a subtle team-inspired emblem.",
        features: [
          "Stretch cotton",
          "Tapered fit",
          "Zip pockets",
          "Elastic cuffs",
        ],
      },
      {
        id: 68,
        title: "Justice League Heritage Cap",
        slug: "justice-league-heritage-cap",
        brand: "MetaWear",
        category: "Accessories",
        character: "Justice League",
        price: 23.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 143,
        stock: 38,
        sizes: ["One Size"],
        colors: ["White", "Navy"],
        image: "/products/justice-league-cap.webp",
        description:
          "Classic team-inspired cap with embroidered front detailing.",
        features: [
          "Adjustable closure",
          "Cotton twill",
          "Embroidered emblem",
          "Curved brim",
        ],
      },
      {
        id: 69,
        title: "League Performance Jacket",
        slug: "league-performance-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "Justice League",
        price: 84.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 88,
        stock: 11,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Navy"],
        image: "/products/league-performance-jacket.webp",
        description:
          "Lightweight performance jacket inspired by superhero training gear.",
        features: [
          "Water-resistant shell",
          "Breathable lining",
          "Zip pockets",
          "Adjustable cuffs",
        ],
      },
      {
        id: 70,
        title: "World's Finest Crewneck",
        slug: "worlds-finest-crewneck",
        brand: "MetaWear",
        category: "Sweatshirts",
        character: "Justice League",
        price: 49.99,
        originalPrice: 59.99,
        currency: "USD",
        rating: 4.8,
        reviewCount: 167,
        stock: 22,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Gray"],
        image: "/products/worlds-finest.webp",
        description:
          "Premium crewneck celebrating the classic partnership of DC heroes.",
        features: [
          "Brushed fleece",
          "Unisex fit",
          "Embroidered graphic",
          "Ribbed cuffs",
        ],
        isSale: true,
      },
    ],
  },

  {
    title: "DC Comics",
    items: [
      {
        id: 71,
        title: "DC Heritage Logo Tee",
        slug: "dc-heritage-logo-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "DC Comics",
        price: 23.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 243,
        stock: 51,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "White", "Gray"],
        image: "/products/dc-heritage.webp",
        description:
          "Minimal graphic tee inspired by decades of superhero storytelling.",
        features: [
          "100% cotton",
          "Classic fit",
          "Minimal graphic",
          "Machine washable",
        ],
      },
      {
        id: 72,
        title: "DC Universe Oversized Tee",
        slug: "dc-universe-oversized-tee",
        brand: "MetaWear",
        category: "T-Shirts",
        character: "DC Comics",
        price: 29.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 174,
        stock: 33,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Washed Black", "Cream"],
        image: "/products/dc-universe.webp",
        description: "Oversized streetwear tee inspired by the DC Universe.",
        features: [
          "Heavyweight cotton",
          "Oversized fit",
          "Vintage wash",
          "Dropped shoulders",
        ],
        isNew: true,
      },
      {
        id: 73,
        title: "Comic Panel Graphic Sweatshirt",
        slug: "comic-panel-graphic-sweatshirt",
        brand: "MetaWear",
        category: "Sweatshirts",
        character: "DC Comics",
        price: 48.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 127,
        stock: 19,
        sizes: ["S", "M", "L", "XL"],
        colors: ["Black", "Gray"],
        image: "/products/comic-panel.webp",
        description:
          "Retro-inspired sweatshirt featuring an original comic-panel layout.",
        features: [
          "Brushed fleece",
          "Relaxed fit",
          "Ribbed cuffs",
          "Cotton blend",
        ],
      },
      {
        id: 74,
        title: "DC Streetwear Hoodie",
        slug: "dc-streetwear-hoodie",
        brand: "MetaWear",
        category: "Hoodies",
        character: "DC Comics",
        price: 57.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 192,
        stock: 21,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Charcoal"],
        image: "/products/dc-streetwear-hoodie.webp",
        description:
          "Heavyweight streetwear hoodie inspired by the wider DC universe.",
        features: [
          "Heavyweight fleece",
          "Oversized fit",
          "Kangaroo pocket",
          "Adjustable hood",
        ],
        isFeatured: true,
      },
      {
        id: 75,
        title: "DC Heroes Bomber Jacket",
        slug: "dc-heroes-bomber-jacket",
        brand: "MetaWear",
        category: "Jackets",
        character: "DC Comics",
        price: 94.99,
        originalPrice: 119.99,
        currency: "USD",
        rating: 4.9,
        reviewCount: 284,
        stock: 7,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["Black", "Olive"],
        image: "/products/dc-premium-bomber.webp",
        description:
          "Premium bomber jacket combining modern streetwear styling with superhero-inspired details.",
        features: [
          "Water-resistant shell",
          "Premium lining",
          "Embroidered details",
          "Ribbed collar and cuffs",
        ],
        isFeatured: true,
        isSale: true,
      },
      {
        id: 76,
        title: "DC Urban Cargo Pants",
        slug: "dc-urban-cargo-pants",
        brand: "MetaWear",
        category: "Pants",
        character: "DC Comics",
        price: 54.99,
        currency: "USD",
        rating: 4.6,
        reviewCount: 94,
        stock: 17,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Olive"],
        image: "/products/dc-cargo-pants.webp",
        description:
          "Modern cargo pants designed for a versatile superhero streetwear look.",
        features: [
          "Cotton twill",
          "Relaxed tapered fit",
          "Multiple utility pockets",
          "Adjustable ankle",
        ],
      },
      {
        id: 77,
        title: "DC Training Shorts",
        slug: "dc-training-shorts",
        brand: "MetaWear",
        category: "Shorts",
        character: "DC Comics",
        price: 31.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 81,
        stock: 29,
        sizes: ["S", "M", "L", "XL"],
        colors: ["White", "Charcoal"],
        image: "/products/dc-training-shorts.webp",
        description:
          "Lightweight athletic shorts with a minimalist superhero-inspired design.",
        features: [
          "Quick-dry fabric",
          "Elastic waistband",
          "Side pockets",
          "Athletic fit",
        ],
      },
      {
        id: 78,
        title: "DC Streetwear Beanie",
        slug: "dc-streetwear-beanie",
        brand: "MetaWear",
        category: "Accessories",
        character: "DC Comics",
        price: 19.99,
        currency: "USD",
        rating: 4.5,
        reviewCount: 129,
        stock: 38,
        sizes: ["One Size"],
        colors: ["White", "Gray", "Navy"],
        image: "/products/dc-beanie.webp",
        description:
          "Soft ribbed beanie designed for a minimalist superhero streetwear look.",
        features: [
          "Soft acrylic knit",
          "Stretch construction",
          "Fold-over cuff",
          "Embroidered detail",
        ],
      },
      {
        id: 79,
        title: "Superhero Canvas Backpack",
        slug: "superhero-canvas-backpack",
        brand: "MetaWear",
        category: "Accessories",
        character: "DC Comics",
        price: 39.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 176,
        stock: 19,
        sizes: ["One Size"],
        colors: ["White", "Navy"],
        image: "/products/superhero-backpack.webp",
        description:
          "Everyday canvas backpack featuring a subtle superhero-inspired design.",
        features: [
          "Durable canvas",
          "Laptop compartment",
          "Padded straps",
          "Front utility pocket",
        ],
        isNew: true,
      },
      {
        id: 80,
        title: "DC Classic Crewneck",
        slug: "dc-classic-crewneck",
        brand: "MetaWear",
        category: "Sweatshirts",
        character: "DC Comics",
        price: 46.99,
        currency: "USD",
        rating: 4.7,
        reviewCount: 154,
        stock: 24,
        sizes: ["S", "M", "L", "XL", "XXL"],
        colors: ["White", "Gray", "Navy"],
        image: "/products/dc-classic-crewneck.webp",
        description:
          "Classic crewneck sweatshirt designed around a timeless superhero aesthetic.",
        features: [
          "Cotton fleece",
          "Regular fit",
          "Embroidered graphic",
          "Ribbed cuffs",
        ],
      },
    ],
  },
];

export default DC_SHOP_DATA2;
